---
clk: 1000000000 # Hz
main_memory: "None" # Infinite 
Glb_memory: 2000000 # Bytes
Glb_tiles: 16 # Number of tiles
Glb_tile_bandwidth: 10000000000 #25.5 #10000000000 # 25.6 # 128 # 307 # bytes per cycles per tile
Glb_mem_mode: "Direct" # Adress for tile needed ot no? Direct - Adressing required, Alltoall - Adressing not required Also memtile mode pakced, unpacked etc
Global_Glb_latency: 200 # 200
Mem_memory: 2000 # Bytes
Mem_tiles: 128 # No of memtiles
Mem_tile_bandwidth: 256 #  1000000000 #256 #256 # 32 * 8 bytes: Bandwidth to a memtiles
Glb_Mem_latency: 1
Bytes_per_element: 2 # Number
