mkdir -p /home/ginasohn/sam-fixed/sam-fixed/data/suitesparse
pushd .
cd /home/ginasohn/sam-fixed/sam-fixed/data/suitesparse
wget https://sparse.tamu.edu/MM/HB/pores_1.tar.gz
wget https://sparse.tamu.edu/MM/FIDAP/ex5.tar.gz
wget https://sparse.tamu.edu/MM/Grund/b1_ss.tar.gz
wget https://sparse.tamu.edu/MM/LPnetlib/lpi_bgprtr.tar.gz
wget https://sparse.tamu.edu/MM/LPnetlib/lpi_itest2.tar.gz
wget https://sparse.tamu.edu/MM/LPnetlib/lpi_itest6.tar.gz
wget https://sparse.tamu.edu/MM/vanHeukelum/cage3.tar.gz
wget https://sparse.tamu.edu/MM/vanHeukelum/cage4.tar.gz
wget https://sparse.tamu.edu/MM/vanHeukelum/cage5.tar.gz
wget https://sparse.tamu.edu/MM/Hamrle/Hamrle1.tar.gz
wget https://sparse.tamu.edu/MM/Oberwolfach/LF10000.tar.gz
wget https://sparse.tamu.edu/MM/Oberwolfach/LF10.tar.gz
wget https://sparse.tamu.edu/MM/Oberwolfach/LFAT5000.tar.gz
wget https://sparse.tamu.edu/MM/Oberwolfach/LFAT5.tar.gz
wget https://sparse.tamu.edu/MM/Pajek/football.tar.gz
wget https://sparse.tamu.edu/MM/Pajek/GD01_c.tar.gz
wget https://sparse.tamu.edu/MM/Pajek/Ragusa16.tar.gz
wget https://sparse.tamu.edu/MM/Pajek/Ragusa18.tar.gz
wget https://sparse.tamu.edu/MM/Meszaros/farm.tar.gz
wget https://sparse.tamu.edu/MM/Meszaros/kleemin.tar.gz
wget https://sparse.tamu.edu/MM/NYPA/Maragal_1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_G5/IG5-6.tar.gz
wget https://sparse.tamu.edu/MM/JGD_GL7d/GL7d10.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/ch3-3-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/ch3-3-b2.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/ch4-4-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/ch5-5-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/ch7-6-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/cis-n4c6-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/cis-n4c6-b13.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/cis-n4c6-b14.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/cis-n4c6-b15.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/klein-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/klein-b2.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/mk9-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n2c6-b10.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n2c6-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n3c4-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n3c4-b2.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n3c4-b3.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n3c4-b4.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n3c5-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n3c6-b10.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n3c6-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n3c6-b11.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n4c5-b10.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n4c5-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n4c5-b11.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n4c6-b10.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n4c6-b11.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n4c6-b1.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n4c6-b12.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n4c6-b13.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n4c6-b14.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Homology/n4c6-b15.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Kocay/Trec5.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Kocay/Trec6.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Kocay/Trec7.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Relat/rel4.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Relat/rel5.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Relat/relat3.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Relat/relat4.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Relat/relat5.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Trefethen/Trefethen_20b.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Trefethen/Trefethen_20.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Trefethen/Trefethen_200b.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Trefethen/Trefethen_200.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Trefethen/Trefethen_2000.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Trefethen/Trefethen_20000b.tar.gz
wget https://sparse.tamu.edu/MM/JGD_Trefethen/Trefethen_20000.tar.gz
wget https://sparse.tamu.edu/MM/Newman/football.tar.gz
popd
