name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: make submodules
      
    - name: Build TACO
      run: make taco/build
      
    - name: Build SAM graphs
      run: make sam
